### ISSUE TITLE
Input f?aed files do not contain the same number of strains and a single instance for each strain

### ISSUE THREAD

**Issue by TheCasualoooo** [vinuesa/get_phylomarkers#14]
Dear get_phylomarkers team,

Hello, I have a question that I would like to request your help with.

I attempted to run "run_get_phylomarkers_pipeline.sh -R 1 -t DNA", but the operation reported an error. 
I have the following data:
ll *faa
Rhizobium_rhizophilum_7209-2.faa
ll *fna
Rhizobium_rhizophilum_7209-2.fna

but getting the error message (log file attached). I saw a previous issue that was very similar to what I am proposing now, but in reality, it seems different

I look forward to hearing from you.

Sincerely,

JL

[run.log](https://github.com/vinuesa/get_phylomarkers/files/12683930/run.log)
[get_phylomarkers_run_AIR1tDNA_k1.5_m0.7_Thigh_21Sep23.log](https://github.com/vinuesa/get_phylomarkers/files/12683931/get_phylomarkers_run_AIR1tDNA_k1.5_m0.7_Thigh_21Sep23.log)

**Comment by TheCasualoooo** [comment]
and i dont know where "get_homologues-est.pl" and "compare_clusters.pl" are.

thanks very much !
(I am not good at english, please forgive my language mistake)

**Comment by eead-csic-compbio** [comment]
> and i dont know where "get_homologues-est.pl" and "compare_clusters.pl" are.
> 
> thanks very much ! (I am not good at english, please forgive my language mistake)

Hi @TheCasualoooo , those two Perl scripts are from package [GET_HOMOLOGUES](https://github.com/eead-csic-compbio/get_homologues), which is the usual tool for producing sequence clusters for GET_PHYLOMARKERS. I assume then you obtained your clusters your own way?

**Comment by eead-csic-compbio** [comment]
> Dear get_phylomarkers team,
> 
> Hello, I have a question that I would like to request your help with.
> 
> I attempted to run "run_get_phylomarkers_pipeline.sh -R 1 -t DNA", but the operation reported an error. I have the following data: ll *faa Rhizobium_rhizophilum_7209-2.faa ll *fna Rhizobium_rhizophilum_7209-2.fna
> 
> but getting the error message (log file attached). I saw a previous issue that was very similar to what I am proposing now, but in reality, it seems different
> 
> I look forward to hearing from you.
> 
> Sincerely,
> 
> JL
> 
> [run.log](https://github.com/vinuesa/get_phylomarkers/files/12683930/run.log) [get_phylomarkers_run_AIR1tDNA_k1.5_m0.7_Thigh_21Sep23.log](https://github.com/vinuesa/get_phylomarkers/files/12683931/get_phylomarkers_run_AIR1tDNA_k1.5_m0.7_Thigh_21Sep23.log)

Are you analyzing a single cluster in FASTA format? If that's the case note you are supposed to feed GET_PHYLOMARKERS a number of  clusters so that the best ones can be selected. Please see the examples at [test_sequences/core_genome)](https://github.com/vinuesa/get_phylomarkers/tree/master/test_sequences/core_genome) to see how the FASTA headers of clusters should look like; note that a taxon name in square brackets is expected. Anything else I might be forgetting @vinuesa ?

**Comment by vinuesa** [comment]
Hi  @TheCasualoooo, i had a look at the provided run.log file, and the problem is clearly stated: you are supposed to run GET_PHYLOMARKERS on single-copy core-genome loci. That means that the  *.fna and *.faa files need to have the same number of sequences from the same list of genomes. This is not the case in your files, as shown below. Run GET_HOMOLOGUES first and use only core genome loci. If necessary, add the -e flag to exclude clusters with inparalogues  

19:09:02 ESC[0;34m# Performing strain composition check on f?aed files ...ESC[0m
14
      1 >10_kDa_chaperonin_1_
      1 >14-alpha-glucan_branching_enzyme_GlgB_
      1 >14-beta-D-glucan_glucohydrolase_
      1 >14-dihydroxy-2-naphthoate_octaprenyltransferase_
      2 >15-anhydro-D-fructose_reductase_

**Comment by vinuesa** [comment]
You may want to read the GET_HOMOLOGUES tutorial for practical tips and key background information at: https://vinuesa.github.io/get_phylomarkers/#get_phylomarkers-tutorial

**Comment by TheCasualoooo** [comment]
After your guidance and suggestions, I think I have learned how to use it initially. Thank you very much

**Comment by vinuesa** [comment]
I'm glad that helped. Do not hesitate in posting further questions if you run into trouble. Cheers
