### ISSUE TITLE
Number of Sequences Error

### ISSUE THREAD

**Issue by jlevy-zymergen** [vinuesa/get_phylomarkers#2]
Hi there,

I am trying to run GET_PHYLOMARKERS on my dataset. I successfully added cds and peptide files 1.faa, 1.fna, 2.faa, 2.fna, ... etc (number denotes strain of same species) to my directory inside of the docker image, and when running the pipeline, I came across this error:

>>> ERROR: Input FASTA files do not contain the same number of sequences...
4584
4671
4707
4924

I took a look at the source code here:

NSEQSFASTA=$(grep -c '^>' ./*.f[na]a | cut -d: -f 2 | sort | uniq | wc -l)
if [ "$NSEQSFASTA" -gt 1 ]
then
  msg " >>> ERROR: Input FASTA files do not contain the same number of sequences..." ERROR RED
  grep -c '^>' ./*.f[na]a | cut -d: -f 2 | sort | uniq 
  exit 4

When I grepped for number of sequence for my coding transcript and peptide file pairs:
4584 1.fna
4584 1.faa
4707 2.fna
4707 2.faa
4924 3.fna
4924 3.faa
4671 4.faa
4671 4.fna

(# sequences in nucleotide coding sequences = # peptide sequences)

And so it seems that all fasta files need to have the same number of sequences. But if the number of CDS elements within each line is different (my goal is to perform orthologous clustering), why must this number be the same? Is there anyway to run the pipeline without this limitation, or how do I run it with this condition?

Thank you for the help.

**Comment by vinuesa** [comment]
Hi, thanks for your message jlevy-zymergen.

Your are right, the problem is that all FASTA files need to have the same number of sequences. The pipeline expects single copy orthologs because those surviving the filtering steps will be concatenated into a supermatrix before being subjected to the final phylogenetic analysis. GET_PHYLO currently does not implement supertree or other approaches that can handle partitions with different numbers of sequences. I could implement an additional runmode that would run all the steps until concatenation, that is, alignment + filtering of gene trees, if you think this would be useful. In that runmode, there would be no need of having the same number of sequences in different clusters. 

One workaround you may want to try is to run GET_HOMOLOGUES or GET_HOMOLOGUES_EST with option -e enabled, so that only single-copy clusters are considered.

Hope this helps clarifying issues. Please don't hesitate in writing again if you need further assistance.
Best,
Pablo
